name: 'Build Vue'
description: 'Build Vuejs for Umbraco V8'
inputs:
  vue-directory:
    description: 'Path to the vue directory'
    required: true
  cd-path-vue:
    description: 'NPM cache dependency path'
    required: true
    default: '**/**.Vue/npm-shrinkwrap.json'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cd-path-vue }}
    - name: NPM install
      run: npm install
      working-directory: ${{ inputs.vue-directory }}
      shell: powershell
    - name: Run webpack
      run: npm run build-prod
      working-directory: ${{ inputs.vue-directory }}
      shell: powershell
